branch-defaults:
  main:
    environment: Flaskcicdapp-env  # Nombre del entorno en Elastic Beanstalk
global:
  application_name: flaskci_cd_app # Nombre de la aplicación en Elastic Beanstalk
  default_platform: Python 3.9
  default_region: us-east-1ß
  profile: null
  workspace_type: Application