branch-defaults:
  main:
    environment: Flaskcicdappp-env  # Nombre del entorno en Elastic Beanstalk
global:
  application_name: flaskci_cd_appp # Nombre de la aplicación en Elastic Beanstalk
  default_platform: Python 3.9
  default_region: us-east-1
  profile: null
  workspace_type: Application