name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install EB CLI
    - name: Install EB CLI
      run: |
        pip install awsebcli
        eb --version  # Verify installation

    # Configure AWS credentials and deploy to Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p python-3.9 flask-beanstalk --region $AWS_REGION
        eb deploy $EB_ENVIRONMENT_NAME
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        EB_APPLICATION_NAME: flaskBeanstalkEnv # Application name in Elastic Beanstalk
        EB_ENVIRONMENT_NAME: FlaskBeanstalkEnv-env
        EB_BUCKET_NAME: flask-beanstalk-bucket
