name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Solo se ejecutará cuando haya un push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install EB CLI
      run: |
        pip install awsebcli

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p python-3.9 flaskci_cd_app --region us-east-1
        eb deploy Flaskcicdappp-env
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        EB_APPLICATION_NAME: flaskci_cd_appp
        EB_ENVIRONMENT_NAME: Flaskcicdappp-env
